version: '3'
services:
  app:
    build: .
    ports:
      - "3200:3200"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=marukaco_root
      - DB_PASSWORD=ncaiev9uqhaichjreihvnvijuavwjnvjo
      - DB_NAME=marukaco_maruka_db
      - PORT=3200
    extra_hosts:
      - "host.docker.internal:host-gateway"