version: '3'
services:
  app:
    build: .
    ports:
      - "3200:3200"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=marukaco_root
      - DB_PASSWORD=ncaiev9uqhaichjreihvnvijuavwjnvjo
      - DB_NAME=marukaco_maruka_db
      - PORT=3200
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ncaiev9uqhaichjreihvnvijuavwjnvjo
      - MYSQL_DATABASE=marukaco_maruka_db
      - MYSQL_USER=marukaco_root
      - MYSQL_PASSWORD=ncaiev9uqhaichjreihvnvijuavwjnvjo
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: