version: '3'
services:
  app:
    build: .
    ports:
      - "3200:3200"
    environment:
      - DB_HOST=db
      - DB_USER=marukaco_root
      - DB_PASSWORD=ncaiev9uqhaichjreihvnvijuavwjnvjo
      - DB_NAME=marukaco_maruka_db
      - PORT=3200  # Add this line to set the port environment variable
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=ncaiev9uqhaichjreihvnvijuavwjnvjo
      - MYSQL_DATABASE=marukaco_maruka_db
    volumes:
      - ./mysql-data:/var/lib/mysql